name: email_auth_firebase_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  device_info_plus: ^10.1.0
  firebase_messaging: ^15.0.2
  firebase_auth: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
